// @ts-nocheck
// Claude-side bridge for auth-provider notifications. Providers (headless under the
// CC proxy) append messages to config/auth-notifications.jsonl via core-auth's
// notify(). This registers a PostToolUse hook + a tiny drain script that reads the
// queue and re-emits each message as a Claude Code hook `systemMessage`, shown to
// the USER but never added to the model's context. (opencode uses toasts instead.)

import { readFileSync, writeFileSync, mkdirSync, existsSync, unlinkSync } from "fs";
import { join } from "path";

// CommonJS so `node <path>` runs it regardless of the surrounding package type.
// The queue is TRANSIENT runtime state, so it lives under cache/ (not config/).
const DRAIN_SCRIPT = `// Auto-generated by claude-code-loader. Drains auth-provider notifications into a
// Claude Code hook systemMessage (user-visible, NOT added to the model's context).
const fs = require("fs"), path = require("path"), os = require("os");
const dir = process.env.CLAUDE_CONFIG_DIR || process.env.HUB_CONFIG_DIR || path.join(os.homedir(), ".claude");
const q = path.join(dir, "cache", "auth-notifications.jsonl");
let msgs = [];
try {
  const t = fs.readFileSync(q, "utf8");
  if (t) { fs.writeFileSync(q, ""); msgs = t.split("\\n").filter(Boolean).map((l) => { try { return JSON.parse(l).message; } catch { return l; } }); }
} catch {}
if (msgs.length) process.stdout.write(JSON.stringify({ systemMessage: msgs.join("\\n"), suppressOutput: true, continue: true }));
`;

// Writes the drain script under cache/ and registers the Stop/PostToolUse hooks;
// also removes any stale auth-notify-drain artifacts left in config/. Idempotent.
export function ensureNotifyDrainHook(configDir) {
  try {
    const cacheSub = join(configDir, "cache");
    if (!existsSync(cacheSub)) mkdirSync(cacheSub, { recursive: true });
    const drainPath = join(cacheSub, "auth-notify-drain.cjs");
    writeFileSync(drainPath, DRAIN_SCRIPT, "utf8");   // refresh in case the script changed

    const settingsPath = join(configDir, "settings.json");
    let settings = {};
    try { settings = JSON.parse(readFileSync(settingsPath, "utf8")); } catch {}
    const hooks = settings.hooks || (settings.hooks = {});
    const cmd = `node "${drainPath}"`;
    // Drain on BOTH Stop (end of every turn, surfaces notifications even when no tool
    // ran, e.g. a plain answer) and PostToolUse (mid-turn, during long tool sequences).
    // Drop any existing auth-notify-drain hook entry first to avoid duplicates.
    let changed = false;
    for (const evt of ["Stop", "PostToolUse"]) {
      const list = hooks[evt] || (hooks[evt] = []);
      const kept = list.filter((entry) => !JSON.stringify(entry).includes("auth-notify-drain"));
      kept.push({ hooks: [{ type: "command", command: cmd }] });
      if (JSON.stringify(kept) !== JSON.stringify(list)) { hooks[evt] = kept; changed = true; }
    }
    if (changed) writeFileSync(settingsPath, JSON.stringify(settings, null, 2), "utf8");

    // The queue and drain script must only live under cache/, never config/.
    for (const stale of [join(configDir, "config", "auth-notify-drain.cjs"), join(configDir, "config", "auth-notifications.jsonl")]) {
      try { if (existsSync(stale)) unlinkSync(stale); } catch { /* ignore */ }
    }
  } catch { /* best-effort, notifications must never break loader activation */ }
}
