// @ts-nocheck
// Claude-side bridge for auth-provider notifications. Providers (headless under the
// CC proxy) append messages to config/auth-notifications.jsonl via core-auth's
// notify(). This registers a PostToolUse hook + a tiny drain script that reads the
// queue and re-emits each message as a Claude Code hook `systemMessage` — shown to
// the USER but never added to the model's context. (opencode uses toasts instead.)

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";

// CommonJS so `node <path>` runs it regardless of the surrounding package type.
const DRAIN_SCRIPT = `// Auto-generated by claude-code-loader. Drains auth-provider notifications into a
// Claude Code hook systemMessage (user-visible, NOT added to the model's context).
const fs = require("fs"), path = require("path"), os = require("os");
const dir = process.env.CLAUDE_CONFIG_DIR || process.env.HUB_CONFIG_DIR || path.join(os.homedir(), ".claude");
const q = path.join(dir, "config", "auth-notifications.jsonl");
let msgs = [];
try {
  const t = fs.readFileSync(q, "utf8");
  if (t) { fs.writeFileSync(q, ""); msgs = t.split("\\n").filter(Boolean).map((l) => { try { return JSON.parse(l).message; } catch { return l; } }); }
} catch {}
if (msgs.length) process.stdout.write(JSON.stringify({ systemMessage: msgs.join("\\n"), suppressOutput: true, continue: true }));
`;

// Idempotently write the drain script + register the PostToolUse hook in settings.json.
export function ensureNotifyDrainHook(configDir) {
  try {
    const cfgSub = join(configDir, "config");
    if (!existsSync(cfgSub)) mkdirSync(cfgSub, { recursive: true });
    const drainPath = join(cfgSub, "auth-notify-drain.cjs");
    writeFileSync(drainPath, DRAIN_SCRIPT, "utf8");   // refresh in case the script changed

    const settingsPath = join(configDir, "settings.json");
    let settings = {};
    try { settings = JSON.parse(readFileSync(settingsPath, "utf8")); } catch {}
    const hooks = settings.hooks || (settings.hooks = {});
    const postTool = hooks.PostToolUse || (hooks.PostToolUse = []);
    if (!JSON.stringify(postTool).includes("auth-notify-drain")) {
      postTool.push({ hooks: [{ type: "command", command: `node "${drainPath}"` }] });
      writeFileSync(settingsPath, JSON.stringify(settings, null, 2), "utf8");
    }
  } catch { /* best-effort — notifications must never break loader activation */ }
}
